### ISSUE TITLE
Add separate class for error page "Go To Home" link positioning

### ISSUE THREAD

**Issue by jaredgorski** [wedeploy/marble#101]
Since the ".link" class currently contains absolute top-right positioning, all links with the proper link styling are positioned this way. We need a separate class for this positioning, so that links can be styled properly but remain inline.

**Comment by jonnilundy** [comment]
@jaredgorski What should the estimation be for this?

**Comment by jaredgorski** [comment]
@jonnilundy should be a 1. I opened it and then made a PR right away: https://github.com/wedeploy/marble/pull/102

still in review
