### ISSUE TITLE
Sidebar list doesn't respect content length

### ISSUE THREAD

**Issue by Robert-Frampton** [wedeploy/marble#11]
Someone using Electric sent me this screenshot.

![image](https://cloud.githubusercontent.com/assets/2466445/22986630/09e38f96-f361-11e6-9711-7bee407054a1.png)

**Comment by zenorocha** [comment]
Yes, also reported on https://github.com/wedeploy/electric/issues/28.

**Comment by zenorocha** [comment]
Can you work on that @ygorcosta?

**Comment by ygorcosta** [comment]
yep!
