### ISSUE TITLE
Button Input Group Bug menu top

### ISSUE THREAD

**Issue by matuzalemsteles** [wedeploy/marble#14]
Hello,

### Description

A bug at the `.input-group-btn`, the same with the `z-index: 3`, overlapping the `topbar` at section **Buttons Addons**. At docs.

### Preview

[Check](http://marblecss.com/docs/components/input-group.html )

**Comment by ygorcosta** [comment]
Fixed =) http://marblecss.com/docs/components/input-group.html
Thank you @matuzalemsteles
