### ISSUE TITLE
topbar margin breaks on guides

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/marble#16]
Running Electric 1.3.2 and Marble 2.4.4

When on `/docs` the header and body elements are working, but when you select a specific guide, the ui breaks near the header.

On Docs home:
<img width="1440" alt="screen shot 2017-03-09 at 4 46 50 pm" src="https://cloud.githubusercontent.com/assets/23219848/23777295/65e3910e-04e8-11e7-9864-80b3407cb321.png">

On a Docs child:
<img width="1440" alt="screen shot 2017-03-09 at 4 47 58 pm" src="https://cloud.githubusercontent.com/assets/23219848/23777289/5d9f3ff2-04e8-11e7-9ef0-93a60e889d1b.png">

**Comment by ygorcosta** [comment]
Hey @jonnilundy 
It was not a problem on marble, but I fixed this issue on https://github.com/wedeploy/generator-electric

you can check the fix to version 1.x here https://github.com/wedeploy/generator-electric/pull/46
and the fix to version 2.x here https://github.com/wedeploy/generator-electric/pull/47
