### ISSUE TITLE
<aside> element not working on tutorials

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/marble#18]
I tried adding this block of code to the tutorials but it was not adding the aside styling like we see in the docs.

I also tried this code in a docs `md` and it worked. 
```
<aside>

###### Something to notice

If you go to `{$page.directory}/hosting/main.js` you will notice some of the Email API logic inside. One call you will use a lot is `post()`, which is the command that sends the email.

</aside>
```

**Comment by ygorcosta** [comment]
@jonnilundy Fixed in version [2.9.7](https://github.com/wedeploy/marble/commit/c54073caa2370346602136ede9b290ce5e94114f)
