### ISSUE TITLE
`icon-16-js-file` missing

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/marble#20]
![image](https://cloud.githubusercontent.com/assets/23219848/26266663/2b4c8c54-3c9b-11e7-8a84-963f370a426b.png)

**Comment by jonnilundy** [comment]
[Mentioned on electricjs.com repo as well.](https://github.com/electricjs/electricjs.com/issues/22)

**Comment by ygorcosta** [comment]
As I said on electric repo... The design team has removed this icon from their gallery. So, marble is not providing this icon anymore.
