### ISSUE TITLE
[marble] Consider more accessible core css

### ISSUE THREAD

**Issue by jonathantneal** [wedeploy/marble#64]
If I want to use parts of marble css, I think I’ll need to manually import the core files like this:

https://github.com/wedeploy/marble/blob/master/packages/marble/src/marble.scss#L1-L22

That might be dangerous to manage all those rewritten imports on the implementation side. Perhaps we could make a marble-core.css file for these situations?

**Comment by ygorcosta** [comment]
LGTM - Could you create this new file and add it to marble.scss?
would be awesome!
GJ!
