### ISSUE TITLE
List font size in blog

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/marble#9]
The font size of the list on the blog is 1.05895rem and I believe that 1rem would match the rest of the text in `<p>`.

**Comment by zenorocha** [comment]
thanks for reporting @jonnilundy, can you send a screenshot for @ygorcosta?

**Comment by jonnilundy** [comment]
Here you go @ygorcosta! :-)
<img width="1058" alt="marble list font size" src="https://cloud.githubusercontent.com/assets/23219848/22519910/17565136-e867-11e6-9c31-0a5a28d5657e.png">

**Comment by ygorcosta** [comment]
Thanks for reporting @jonnilundy 
Actually, the correct value is 1.05895rem :)
